# This file was generated by GoReleaser. DO NOT EDIT.
cask "stormlight" do
  version "0.12.2"

  on_macos do
    on_intel do
      sha256 "87e135b0610b9f4c273d0d57e7d530e95e5211f691d8f94fefba87368c21422a"
      url "https://github.com/trentkm/stormlight/releases/download/v#{version}/stormlight_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d82dc18e7054ef0db6f70963e6317a1af47579a687e6d892e536c04f241ade39"
      url "https://github.com/trentkm/stormlight/releases/download/v#{version}/stormlight_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1a471e6bfd452b1dac86a73138b02e4e49de7252121e9ca6bfb0f212281988cf"
      url "https://github.com/trentkm/stormlight/releases/download/v#{version}/stormlight_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f272fd7b730a94799f247834c25c148f1dde67367df191803b3417b1347206ff"
      url "https://github.com/trentkm/stormlight/releases/download/v#{version}/stormlight_#{version}_linux_arm64.tar.gz"
    end
  end

  name "stormlight"
  desc "Workspace-native control surface for coding agents"
  homepage "https://github.com/trentkm/stormlight"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "yazi",
    ]

  binary "stormlight"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stormlight"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Optional: install neovim to edit agent tasks in a popup (brew install neovim).
  EOS
end
