# This file was generated by GoReleaser. DO NOT EDIT.
cask "stormlight" do
  version "0.14.0"

  on_macos do
    on_arm do
      sha256 "1bd9452443f170e85e670ea9867c3e32ac6228415a1155677d7bad7df371e214"
      url "https://github.com/trentkm/stormlight/releases/download/v#{version}/stormlight_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "04184cbdf8968f430df039dc54eb4b6c98a24a4be20d66eef5891addc02f0b64"
      url "https://github.com/trentkm/stormlight/releases/download/v#{version}/stormlight_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5dbf536457d63bc32f302a809306979518308969555b9d3ff73fa697bbdb13ac"
      url "https://github.com/trentkm/stormlight/releases/download/v#{version}/stormlight_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5e39f39d1556221727d6100c6ead7c859e9a90bf36a2e7180e365de9353712d3"
      url "https://github.com/trentkm/stormlight/releases/download/v#{version}/stormlight_#{version}_linux_amd64.tar.gz"
    end
  end

  name "stormlight"
  desc "Workspace-native control surface for coding agents"
  homepage "https://github.com/trentkm/stormlight"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "yazi",
    ]

  binary "stormlight"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stormlight"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Optional: install neovim to edit agent tasks in a popup (brew install neovim).
  EOS
end
