# This file was generated by GoReleaser. DO NOT EDIT.
cask "stormlight" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "61b271944e402fb536c225a87db8770427b0ad2422fed9b68e98894accad0cce"
      url "https://github.com/trentkm/stormlight/releases/download/v#{version}/stormlight_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cd97dc86f10f550571c7108eb838f146a36a9fe826d08ccfc51f362551b60162"
      url "https://github.com/trentkm/stormlight/releases/download/v#{version}/stormlight_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d4d7b196eaf4d2efd418746b0e9d9bd32ed70e9d42f89a84551699d5336a8699"
      url "https://github.com/trentkm/stormlight/releases/download/v#{version}/stormlight_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "50661bddfaaa662c2cf21badc42b0e12108687eddd13a6192dd064422ae770d2"
      url "https://github.com/trentkm/stormlight/releases/download/v#{version}/stormlight_#{version}_linux_arm64.tar.gz"
    end
  end

  name "stormlight"
  desc "Workspace-native control surface for coding agents"
  homepage "https://github.com/trentkm/stormlight"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "yazi",
    ]

  binary "stormlight"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stormlight"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Optional: install neovim to edit agent tasks in a popup (brew install neovim).
  EOS
end
