# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stormlight < Formula
  desc "Workspace-native control surface for coding agents"
  homepage "https://github.com/trentkm/stormlight"
  version "0.2.2"
  license "MIT"

  depends_on "tmux"
  depends_on "yazi"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trentkm/stormlight/releases/download/v0.2.2/stormlight_0.2.2_darwin_amd64.tar.gz"
      sha256 "f6aa609aada258052b930ab5eb3c6ac04919d7971217a5aeeb298b923a18c034"

      define_method(:install) do
        bin.install "stormlight"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trentkm/stormlight/releases/download/v0.2.2/stormlight_0.2.2_darwin_arm64.tar.gz"
      sha256 "4cd33332ba02db4a04d09ec0f1b8c5068af61528546e7a691b49a4eee16472c4"

      define_method(:install) do
        bin.install "stormlight"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/trentkm/stormlight/releases/download/v0.2.2/stormlight_0.2.2_linux_amd64.tar.gz"
      sha256 "a4866e458f62172af1d5ad186b9945e454b9b70d3967bb04a5e23d1b8eb5cedb"
      define_method(:install) do
        bin.install "stormlight"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trentkm/stormlight/releases/download/v0.2.2/stormlight_0.2.2_linux_arm64.tar.gz"
      sha256 "28c4f5e8cf5bc64d900196af23ba499cb55e3d2a43d7e6ec308f1bfda2fd2de8"
      define_method(:install) do
        bin.install "stormlight"
      end
    end
  end

  def caveats
    <<~EOS
      Optional: install neovim to edit agent tasks in a popup (brew install neovim).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/stormlight --version")
  end
end
