# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stormlight < Formula
  desc "Workspace-native control surface for coding agents"
  homepage "https://github.com/trentkm/stormlight"
  version "0.3.0"
  license "MIT"

  depends_on "tmux"
  depends_on "yazi"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trentkm/stormlight/releases/download/v0.3.0/stormlight_0.3.0_darwin_amd64.tar.gz"
      sha256 "97ea1f0a2ef2abec90fd0e81c09aed1d0929a6b8c09f4583ecf97b44fe11b691"

      define_method(:install) do
        bin.install "stormlight"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trentkm/stormlight/releases/download/v0.3.0/stormlight_0.3.0_darwin_arm64.tar.gz"
      sha256 "04ee6d0aafd042d3866adacd9423b1711ffa4e81e012b74ed1dbf6b088b1c3cd"

      define_method(:install) do
        bin.install "stormlight"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/trentkm/stormlight/releases/download/v0.3.0/stormlight_0.3.0_linux_amd64.tar.gz"
      sha256 "db50db8c7cc889bac7d5a409f1ed760c3468035d8a10d7853ed4f30c2ef832b6"
      define_method(:install) do
        bin.install "stormlight"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trentkm/stormlight/releases/download/v0.3.0/stormlight_0.3.0_linux_arm64.tar.gz"
      sha256 "1025d1850514f5c447636338495fd6f63927d1413eedac211119bdd9118e7627"
      define_method(:install) do
        bin.install "stormlight"
      end
    end
  end

  def caveats
    <<~EOS
      Optional: install neovim to edit agent tasks in a popup (brew install neovim).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/stormlight --version")
  end
end
